apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: backend-tests-go-kpfyfjfx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: backend-tests-go-kpfyfjfx 
  name: backend-tests-go-kpfyfjfx
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: backend-tests-go-kpfyfjfx
    weight: 100 
